apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: false
spec:
  ingressClassName: nginx
  rules:
    - host: your-domain-here.com # If you have NO domain, remove host: line
      http:
        paths:
          - path: /api/v1/appointment
            pathType: Prefix
            backend:
              service:
                name: appointment
                port:
                  number: 8081

          - path: /api/v1/doctor
            pathType: Prefix
            backend:
              service:
                name: doctor
                port:
                  number: 8082

          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 3000
